### ISSUE TITLE
JavaScript Exception

### ISSUE THREAD

**Issue by kasraqq** [fjcaetano/ReCaptcha#7]
I got this exception most of the times when I run the app on device, and sometimes on simulator. I can not find the root cause. Any idea?

`Error Domain=WKErrorDomain Code=4 "A JavaScript exception occurred" UserInfo={WKJavaScriptExceptionLineNumber=11, WKJavaScriptExceptionMessage=TypeError: Argument 1 ('target') to MutationObserver.observe must be an instance of Node, WKJavaScriptExceptionSourceURL=http://localhost/, NSLocalizedDescription=A JavaScript exception occurred, WKJavaScriptExceptionColumnNumber=13}))`

**Comment by fjcaetano** [comment]
I was able to run it fine in every device I tested. Could you provide some info on the stack you're using? Xcode version, device name, iOS version, etc. It might be nice to check if you have correctly configured the ReCaptcha key.

Also, could you try running the example project in your device?

**Comment by kasraqq** [comment]
I’m already testing the example provided on git, 
I got the error on any device, as an example: iPhone5s, iOS version 10.2.1, Xcode 8.2.1
The recaptcha key is also configured correctly. It’s nice to know that, works perfectly on simulator, but not on device.

**Comment by kasraqq** [comment]
The exception happens here:

  var execute = function() {
    observeDOM(document.getElementsByTagName("div")[3], function() {
      window.webkit.messageHandlers.recaptcha.postMessage({action: "showReCaptcha"});
    });

when  document.getElementsByTagName("div")[3] is not an instance of node.

here is the error:
Error Domain=WKErrorDomain Code=4 "A JavaScript exception occurred" UserInfo={WKJavaScriptExceptionLineNumber=11, WKJavaScriptExceptionMessage=TypeError: Argument 1 ('target') to MutationObserver.observe must be an instance of Node, WKJavaScriptExceptionSourceURL=http://localhost/, NSLocalizedDescription=A JavaScript exception occurred, WKJavaScriptExceptionColumnNumber=13}))

**Comment by fjcaetano** [comment]
I was able to reproduce it on an iPhone SE running iOS 9.3 when I changed to an invalid key.

Could you try running this and paste the result here?
```
webView.evaluateJavaScript("document.getElementsByClassName('grecaptcha-user-facing-error')[0].innerHTML") { result, error in
    print(result)
    print(error)
}
```

If it prints `ERROR for site owner: Invalid site key` it is likely that you're using the wrong key, though your domain might be configured correctly. Please, try checking if you didn't set it up with the server key instead of the client key. 

<img width="977" alt="screen shot 2017-09-22 at 16 32 17" src="https://user-images.githubusercontent.com/1066295/30761214-d783cb7e-9fb3-11e7-97e6-4695ce53509b.png">

**Comment by fjcaetano** [comment]
Btw, also don't forget checking if you've setup an Invisible reCAPTCHA key. If you try using a reCAPTCHA v2 key, the framework won't work.

**Comment by kasraqq** [comment]
Thanks for the supporting.

here is the result when I replace 

(Error Domain=WKErrorDomain Code=4 "A JavaScript exception occurred" UserInfo={WKJavaScriptExceptionLineNumber=1, WKJavaScriptExceptionMessage=TypeError: undefined is not an object (evaluating 'document.getElementsByClassName('grecaptcha-user-facing-error')[0].innerHTML'), WKJavaScriptExceptionSourceURL=my domain, NSLocalizedDescription=A JavaScript exception occurred, WKJavaScriptExceptionColumnNumber=67})

when I replace with:
webView.evaluateJavaScript("document.getElementsByClassName('grecaptcha-user-facing-error')[0].innerHTML") { result, error in
            print(result)
            print(error)
        }
The fact is that sometimes it works, so shows that the site key and domain are set correctly. 
There is another question, what if I have more than one domains? is there any way I can pass an array of domains?

**Comment by fjcaetano** [comment]
I'm sorry, I just now realized that the test I gave you doesn't work on iOS, only on web browsers.

The fact that it does work sometimes is an improvement. You need to try and find out what causes the intermittence. The only way I could reproduce the original error you gave me was with a wrong public key.

There's no way to send an array of domains, nor there's no need to it. If you need to use a different domain, you can send it to the ReCaptcha class initialized [as it is in the docs](http://cocoadocs.org/docsets/ReCaptcha/0.2.0/Classes/ReCaptcha.html#/s:FC9ReCaptcha9ReCaptchacFzT6apiKeyGSqSS_7baseURLGSqV10Foundation3URL__S0_). Under the hood, ReCaptcha uses `WKWebView.loadHTMLString(_:baseURL:)` which expects an URL, so you really can't provide an array.

**Comment by hqy2000** [comment]
Same issue. It works fine on simulators, but crashes on real devices. 
The error log is the same.

**Comment by kasraqq** [comment]
I have found the issue and it has been fixed, you can try as well. When you load the Webview for the first time,( it means when you call the ReCaptchaWebViewManager init method) you should set the size of Webview and the Webview must be added as subview to desired view, before you call the webView.loadHTMLString. If you do so, and you implement this
 `public func webView(_ webView: WKWebView, decidePolicyFor navigationResponse: WKNavigationResponse, decisionHandler: @escaping (WKNavigationResponsePolicy) -> Void) ` delegate method, you will see these 2 resources are loaded `https://www.google.com/recaptcha/api2/anchor? and https://www.google.com/recaptcha/api2/bframe?`. When the one with bframe is done, it means the view is loaded and user can press the validate, otherwise you will see the JS exception.

**Comment by fjcaetano** [comment]
That is super weird. How did you manage to do that? When calling `validate(on: UIView)` it adds the WKWebView to the given view before executing the API. Did you, by any chance, sent a view that wasn't in the window hierarchy? I wonder if there should be some validation for that.

Also, how were you able to fix it? Or was it fixed with the current changes?

**Comment by fjcaetano** [comment]
@kasraqq I applied some changes based on your comment. Could you take a look at the commit above and try it out to check if the issue was solved?

**Comment by hqy2000** [comment]
@fjcaetano The issue was solved in my app.
btw, can you change the javascript to this url (https://www.recaptcha.net/recaptcha/api.js) so that people in China can use it?

**Comment by fjcaetano** [comment]
@mmlmml1 no problem, could you create a separate issue for that since it's not related to the exception?

@kasraqq It'd also be great to hear if the fix solved the issue for you as well since you were the one who brought it up

**Comment by kasraqq** [comment]
@fjcaetano Sorry for delayed response. I'm too much busy these days. I will send a quick feedback asap.

**Comment by fjcaetano** [comment]
Closing due to inactivity

**Comment by manderson420** [comment]
@fjcaetano This is still broken on version 1.0.1 for us. iOS 11.0 device iPhone 6 device. This ONLY seems to be an issue on iOS 11.0 so far. We are getting the following error from the ReCaptcha library: ```Error Domain=WKErrorDomain Code=4 "A JavaScript exception occurred" UserInfo={WKJavaScriptExceptionLineNumber=16, WKJavaScriptExceptionMessage=TypeError: undefined is not an object (evaluating 'document.getElementsByTagName("div")[4].outerHTML = ""'), WKJavaScriptExceptionColumnNumber=44, WKJavaScriptExceptionSourceURL=https://ourdomain.com/, NSLocalizedDescription=A JavaScript exception occurred}```

The curious thing is that this causes an exception every other time we kick off the ReCaptcha webview flow. The following time we get a successful result. Any ideas?

**Comment by fjcaetano** [comment]
@manderson420 that seems to be a different error. It appears to have been introduced with 78fa352220b698af141964bb64e362c77f49159f, since it fails on `getElementsByTagName("div")[4]`.

Could you open a new issue so we can address this?

Also, as a workaround, could you try removing that line from `recaptcha.html` to check if the issue stops?

**Comment by manderson420** [comment]
Sure, I'll open a new ticket with the details I posted 👍 

I don't have access to the testing device with iOS 11.0 at the moment but will have an update for you when we're back from the holidays.
